server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Todas las rutas van a index.html (Angular Router fallback)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Caché para estáticos
    location ~* \.(?:ico|css|js|gif|jpe?g|png)$ {
        expires max;
        add_header Cache-Control "public, max-age=31536000";
    }

    # Deshabilitar acceso a archivos ocultos
    location ~ /\. {
        deny all;
    }
}
